"""
Django settings for django_server project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import os.path as path
from pathlib import Path

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv():
    dotenv_path = path.join(BASE_DIR, ".env")
    example_dotenv_path = path.join(BASE_DIR, ".env.example")

    env_path = dotenv.find_dotenv(filename=dotenv_path)
    if not env_path:
        env_path = dotenv.find_dotenv(filename=example_dotenv_path)

    if env_path:
        dotenv.load_dotenv(env_path)

    dotenv.load_dotenv(dotenv_path)


load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
IS_PRODUCTION = os.getenv("IS_PRODUCTION", "false") == "true"

if IS_PRODUCTION and not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable must be set in production.")

if not SECRET_KEY:
    SECRET_KEY = "django-insecure-dev-only-key-change-in-production"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CORS_ALLOWS_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "UNAUTHENTICATED_USER": None,
}

# Application definition

INSTALLED_APPS = [
    # Third-party apps
    "corsheaders",
    "rest_framework",
    "channels",
    "daphne",
    # Django apps
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    # My apps
    "django_app",
    "container",
]

# Websocket
ASGI_APPLICATION = "django_server.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "django_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "django_server.wsgi.application"


# Database
LOCAL_DATABASE_HOST = os.getenv("LOCAL_DATABASE_HOST")
DOCKER_DATABASE_HOST = os.getenv("DOCKER_DATABASE_HOST")
PRODUCTION_DATABASE_HOST = os.getenv("PRODUCTION_DATABASE_HOST")

IS_DOCKER = os.getenv("DOCKER", "false") == "true"

if IS_PRODUCTION and PRODUCTION_DATABASE_HOST:
    DATABASE_HOST = PRODUCTION_DATABASE_HOST
elif IS_DOCKER and DOCKER_DATABASE_HOST:
    DATABASE_HOST = DOCKER_DATABASE_HOST
elif LOCAL_DATABASE_HOST:
    DATABASE_HOST = LOCAL_DATABASE_HOST
else:
    exit("No database host specified")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME"),
        "HOST": DATABASE_HOST,
        "PORT": int(os.getenv("DATABASE_PORT", "5432")),
        "USER": os.getenv("DATABASE_USERNAME"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
            "propagate": False,
        },
        "django_app": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "container": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
