# Generated by Django 4.1.13 on 2024-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='title',
            field=models.TextField(default='New chat'),
        ),
    ]
