# Generated by Django 4.1.13 on 2024-11-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
