# Generated by Django 4.1.13 on 2024-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_chathistory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
