# Generated by Django 4.1.13 on 2025-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
